# Generated by Django 3.2.11 on 2022-02-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_compartment_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail_processed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='component.category'),
        ),
    ]
