# Generated by Django 3.2.11 on 2022-02-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_auto_20220203_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail_processed',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
    ]
