# Generated by Django 3.2.11 on 2022-02-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_alter_category_thumbnail_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail_processed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
